[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[env]
TERM="xterm-256color"

[shell]
program = "tmux" # <- set this to the path of your tmux installation

# [font]
# size = 12.0
# [font.bold]
# family="BlexMono Nerd Font"
# style = "Bold"
#
# [font.bold_italic]
# family="BlexMono Nerd Font"
# style = "Bold Italic"
#
# [font.italic]
# family="BlexMono Nerd Font"
# style = "Italic"
#
# [font.normal]
# family="BlexMono Nerd Font"
# style = "Regular"


[font.normal]
family="0xProto Nerd Font Mono"
style = "Regular"

[colors]


[selection]
save_to_clipboard = true

[window]
startup_mode =  "Fullscreen"
padding = { x = 16 , y = 16 }
